// <auto-generated />
namespace SelfOrganization.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Init_Project : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_Project));
        
        string IMigrationMetadata.Id
        {
            get { return "201403040312105_Init_Project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
