// <auto-generated />
namespace SelfOrg_2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Init_Project_Models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_Project_Models));
        
        string IMigrationMetadata.Id
        {
            get { return "201403040337047_Init_Project_Models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
